# Generated by Django 5.1.2 on 2024-10-30 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.image')),
            ],
        ),
    ]
